DROP DATABASE IF EXISTS its_32_06_oto_carta;
CREATE DATABASE its_32_06_oto_carta;
USE its_32_06_oto_carta;

CREATE TABLE Persona(
	personaID INTEGER PRIMARY KEY AUTO_INCREMENT,
    nominativo VARCHAR(500) NOT NULL
);

CREATE TABLE Carta(
	cartaID INTEGER PRIMARY KEY AUTO_INCREMENT,
    codice VARCHAR(10) NOT NULL,
    personaRIF INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (personaRIF) REFERENCES Persona(personaID) ON DELETE CASCADE
);